### ISSUE TITLE
Number reported are doubled

### ISSUE THREAD

**Issue by thomasfla** [OpenJarbas/covid_reports#3]
It seems that all the numbers of cases reported by the API are doubled. Maybe since 'World' is in the list? 

```
c.global_data()
{'new_deaths': 286,
 'date': '2020/04/06',
 'total_recovered': 532916,
 'active_cases': 1882356,
 'total_deaths': 139136,
 'new_cases': 8684,
 'country': 'world',
 'total_cases': 2554408,
 'critical': 91804}
```

**Comment by JarbasAl** [comment]
either i missed that or world was not in the grid when i wrote this scrapper... either way its fixed! thx for reporting!
